# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 20, 2, 44, 5, 713322, tzinfo=utc)),
        ),
    ]
